// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvNw4wiuIyZw5HpxrNkZ5zGxNcHVxxMzU',
    appId: '1:933518466688:web:bad389d953e2917645d065',
    messagingSenderId: '933518466688',
    projectId: 'monami-a87b6',
    authDomain: 'monami-a87b6.firebaseapp.com',
    storageBucket: 'monami-a87b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADivyglwjc1uT9wsoSL9JLhC-_DfEzBMM',
    appId: '1:933518466688:android:78bf91ccaf5bc0e045d065',
    messagingSenderId: '933518466688',
    projectId: 'monami-a87b6',
    storageBucket: 'monami-a87b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtMWJ6b18ll8LheMuSTsZdg5L8YaQFPsM',
    appId: '1:933518466688:ios:090f207415b7679a45d065',
    messagingSenderId: '933518466688',
    projectId: 'monami-a87b6',
    storageBucket: 'monami-a87b6.appspot.com',
    iosBundleId: 'com.example.monami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtMWJ6b18ll8LheMuSTsZdg5L8YaQFPsM',
    appId: '1:933518466688:ios:d99ad33aec22d9e045d065',
    messagingSenderId: '933518466688',
    projectId: 'monami-a87b6',
    storageBucket: 'monami-a87b6.appspot.com',
    iosBundleId: 'com.example.monami.RunnerTests',
  );
}
