// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4mh8RTb5TkXBHudU3W1IJulTiXwGo5Yw',
    appId: '1:124866980375:web:1ae386228a6c049fb70a52',
    messagingSenderId: '124866980375',
    projectId: 'monami-88d95',
    authDomain: 'monami-88d95.firebaseapp.com',
    storageBucket: 'monami-88d95.appspot.com',
    measurementId: 'G-65LMXWP8X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwglkEj_YNB5p3xe0CXe-lYrNzXsZ9C7g',
    appId: '1:124866980375:android:1895d91cdf730f8bb70a52',
    messagingSenderId: '124866980375',
    projectId: 'monami-88d95',
    storageBucket: 'monami-88d95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQTGHK0PMoiUywkpEq-eQZJo5yp7_j6mQ',
    appId: '1:124866980375:ios:b625c5f171dccc08b70a52',
    messagingSenderId: '124866980375',
    projectId: 'monami-88d95',
    storageBucket: 'monami-88d95.appspot.com',
    iosBundleId: 'com.example.monami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQTGHK0PMoiUywkpEq-eQZJo5yp7_j6mQ',
    appId: '1:124866980375:ios:4b8e717c566f2357b70a52',
    messagingSenderId: '124866980375',
    projectId: 'monami-88d95',
    storageBucket: 'monami-88d95.appspot.com',
    iosBundleId: 'com.example.monami.RunnerTests',
  );
}
